-- 1. SECTIONS TABLE
--------------------------------------------------------------------
CREATE TABLE sections (
    section_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_name    VARCHAR2(50) NOT NULL UNIQUE
) TABLESPACE tw_data;

--------------------------------------------------------------------
-- 2. CHILDREN TABLE
--------------------------------------------------------------------
CREATE TABLE children (
    child_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name           VARCHAR2(100) NOT NULL,
    date_of_birth       DATE NOT NULL,
    gender              VARCHAR2(10) CHECK (gender IN ('Male','Female')),
    disability_status   VARCHAR2(3) CHECK (disability_status IN ('Yes','No')),
    section_id          NUMBER,
    CONSTRAINT fk_child_section
        FOREIGN KEY (section_id)
        REFERENCES sections(section_id)
) TABLESPACE tw_data;

-- INDEX for better join speed
CREATE INDEX idx_children_section ON children(section_id) TABLESPACE tw_index;

--------------------------------------------------------------------
-- 3. EDUCATION TABLE
--------------------------------------------------------------------
CREATE TABLE education (
    education_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id            NUMBER NOT NULL,
    school_name         VARCHAR2(100) NOT NULL,
    grade_level         VARCHAR2(30),
    performance_notes   VARCHAR2(200),
    CONSTRAINT fk_edu_child
        FOREIGN KEY (child_id)
        REFERENCES children(child_id)
) TABLESPACE tw_data;

CREATE INDEX idx_edu_child ON education(child_id) TABLESPACE tw_index;

--------------------------------------------------------------------
-- 4. STAFF TABLE
--------------------------------------------------------------------
CREATE TABLE staff (
    staff_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR2(100) NOT NULL,
    position        VARCHAR2(50) NOT NULL,
    contact_number  VARCHAR2(15) UNIQUE
) TABLESPACE tw_data;

--------------------------------------------------------------------
-- 5. SUPPORT_SERVICES TABLE
--------------------------------------------------------------------
CREATE TABLE support_services (
    service_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_type    VARCHAR2(50) NOT NULL,
    description     VARCHAR2(200),
    child_id        NUMBER,
    staff_id        NUMBER,
    service_date    DATE DEFAULT SYSDATE,
    CONSTRAINT fk_serv_child
        FOREIGN KEY (child_id)
        REFERENCES children(child_id),
    CONSTRAINT fk_serv_staff
        FOREIGN KEY (staff_id)
        REFERENCES staff(staff_id)
) TABLESPACE tw_data;

CREATE INDEX idx_service_child ON support_services(child_id) TABLESPACE tw_index;
CREATE INDEX idx_service_staff ON support_services(staff_id) TABLESPACE tw_index;






CREATE TABLE holidays (
    holiday_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_name VARCHAR2(100) NOT NULL,
    holiday_date DATE NOT NULL,
    holiday_type VARCHAR2(50) CHECK (holiday_type IN ('Public', 'Religious', 'National')),
    is_recurring VARCHAR2(3) CHECK (is_recurring IN ('Yes', 'No')),
    description VARCHAR2(200),
    created_date DATE DEFAULT SYSDATE,
    created_by VARCHAR2(100) DEFAULT USER,
    CONSTRAINT unique_holiday_date UNIQUE (holiday_date)
) TABLESPACE tw_data;

-- Index for date-based queries
CREATE INDEX idx_holidays_date ON holidays(holiday_date) TABLESPACE tw_index;
CREATE INDEX idx_holidays_month ON holidays(EXTRACT(MONTH FROM holiday_date)) TABLESPACE tw_index;




CREATE TABLE dml_audit_log (
    audit_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(100) NOT NULL,
    operation_type VARCHAR2(20) NOT NULL CHECK (operation_type IN ('INSERT', 'UPDATE', 'DELETE')),
    user_name VARCHAR2(100) DEFAULT USER,
    session_id VARCHAR2(50),
    machine_name VARCHAR2(100),
    os_user VARCHAR2(100),
    ip_address VARCHAR2(50),
    old_values CLOB,
    new_values CLOB,
    affected_rows NUMBER,
    operation_status VARCHAR2(20) DEFAULT 'SUCCESS' CHECK (operation_status IN ('SUCCESS', 'FAILURE')),
    error_message VARCHAR2(4000),
    business_rule_violated VARCHAR2(500),
    child_id NUMBER,
    staff_id NUMBER,
    audit_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    CONSTRAINT fk_audit_child FOREIGN KEY (child_id) REFERENCES children(child_id),
    CONSTRAINT fk_audit_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id) 
);



CREATE TABLE ERROR_LOG (
    ERROR_ID        NUMBER,
    PROCEDURE_NAME  VARCHAR2(100),
    ERROR_CODE      NUMBER,
    ERROR_MESSAGE   VARCHAR2(1000),
    CHILD_ID        NUMBER,
    ERROR_DATE      DATE,
    USER_NAME       VARCHAR2(100)
);








